interface:
    resource: "@InterfaceBundle/Resources/config/routing.yml"
    prefix:   /

#core:
#    resource: "@CoreBundle/Controller/"
#    type:     annotation
#    prefix:   /

#api:
#    resource: "@ApiBundle/Controller/"
#    type:     annotation
#    prefix:   /

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /v1

logout:
    path: /logout

