
apiCreateTerminal:
    path:                       /terminal
    defaults:                   { _controller: ApiBundle:DeviceReader:create }
    methods:                    [POST]

apiCreateDevice:
    path:                       /terminal/{id}/device
    defaults:                   { _controller: ApiBundle:Device:create }
    methods:                    [POST]
    requirements:
      id:                       \d+

apiCheckEntry:
    path:                       /terminal/{id}/entry
    defaults:                   { _controller: ApiBundle:Entry:check }
    methods:                    [POST]
    requirements:
      id:                       \d+

apiCreateLog:
    path:                       /terminal/{id}/log
    defaults:                   { _controller: ApiBundle:Log:create }
    methods:                    [POST]
    requirements:
      id:                       \d+


